package com.ivan.study.transaction.domain;

import java.util.Date;

public class Trade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.trade_no
     *
     * @mbggenerated Tue Nov 28 10:35:54 CST 2017
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.trade_payer
     *
     * @mbggenerated Tue Nov 28 10:35:54 CST 2017
     */
    private String tradePayer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.trade_gather
     *
     * @mbggenerated Tue Nov 28 10:35:54 CST 2017
     */
    private String tradeGather;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.amount
     *
     * @mbggenerated Tue Nov 28 10:35:54 CST 2017
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.create_time
     *
     * @mbggenerated Tue Nov 28 10:35:54 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.trade_no
     *
     * @return the value of trade.trade_no
     *
     * @mbggenerated Tue Nov 28 10:35:54 CST 2017
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.trade_no
     *
     * @param tradeNo the value for trade.trade_no
     *
     * @mbggenerated Tue Nov 28 10:35:54 CST 2017
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.trade_payer
     *
     * @return the value of trade.trade_payer
     *
     * @mbggenerated Tue Nov 28 10:35:54 CST 2017
     */
    public String getTradePayer() {
        return tradePayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.trade_payer
     *
     * @param tradePayer the value for trade.trade_payer
     *
     * @mbggenerated Tue Nov 28 10:35:54 CST 2017
     */
    public void setTradePayer(String tradePayer) {
        this.tradePayer = tradePayer == null ? null : tradePayer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.trade_gather
     *
     * @return the value of trade.trade_gather
     *
     * @mbggenerated Tue Nov 28 10:35:54 CST 2017
     */
    public String getTradeGather() {
        return tradeGather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.trade_gather
     *
     * @param tradeGather the value for trade.trade_gather
     *
     * @mbggenerated Tue Nov 28 10:35:54 CST 2017
     */
    public void setTradeGather(String tradeGather) {
        this.tradeGather = tradeGather == null ? null : tradeGather.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.amount
     *
     * @return the value of trade.amount
     *
     * @mbggenerated Tue Nov 28 10:35:54 CST 2017
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.amount
     *
     * @param amount the value for trade.amount
     *
     * @mbggenerated Tue Nov 28 10:35:54 CST 2017
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.create_time
     *
     * @return the value of trade.create_time
     *
     * @mbggenerated Tue Nov 28 10:35:54 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.create_time
     *
     * @param createTime the value for trade.create_time
     *
     * @mbggenerated Tue Nov 28 10:35:54 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}